### ISSUE TITLE
Add hookable methods (Feature Request)

### ISSUE THREAD

**Issue by netcarver** [ryancramerdesign/FileValidatorImage#1]
@ryancramerdesign 

This is a very welcome module, thank-you Ryan.

Please could you make hasBadExif() hookable,
Also, can we provide extra validation checks by hooking something in here like a stub ___extraChecks() method?

**Comment by ryancramerdesign** [comment]
@netcarver No problem, I have added this. The hookable extraChecks method is named isValidHook so that the method name still communicates something about the return value (true=valid, false=not valid).

**Comment by netcarver** [comment]
Perfect, thank you.
